name: PaperPlugin
version: '${project.version}'
main: fourtyseven.paperplugin.PaperPlugin

commands:
  wallet:
    description: Erhalten eines Wallets
  createplot:
    description: Erstellen eines Plots
  addpermission:
    description: Hinzufuegen einer Permission
  createBankAccount:
    description: Creates Bankaccount
  addMoney:
    description: Add Money to Users Bank Account
  npc:
    description: Spawn an NPC

